import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import UrgentUpdates from '../../components/UrgentUpdates';
import ModeToggle from '../../components/ModeToggle';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 16px', borderBottom: '1px solid #eee' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <a href="/" style={{ fontWeight: 700, fontSize: 16, textDecoration: 'none', color: 'inherit' }}>Global Education Hub</a>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
            <ModeToggle />
          </div>
        </header>
        <UrgentUpdates />
        {children}
      </body>
    </html>
  );
}
